### ISSUE TITLE
Autres commandes API dispo ?

### ISSUE THREAD

**Issue by Yann0128** [shun84/jeedom-plugin-mullerintuitiv#1]
Bonjour, 
Votre package m’a été d’une grande aide, merci beaucoup.
Je cherche à récupérer d’autres informations depuis les API comme la consommation électrique de mes radiateurs. Est ce que vous auriez la liste des commandes API de Muller Intuitiv ?

**Comment by shun84** [comment]
Hello,

Sur la branche beta, je récupère la consommation électrique

Cordialement

**Comment by Yann0128** [comment]
Roh merci, je ne l'avais pas vu. J'ai pu intégrer cette commande API dans mon modèle Node Red mais je galère à intégrer les différents paramètres au POST HTTP : j'obtiens des erreurs code 21 (Invalid array arg) à chaque essai. Vous aviez eu ce genre de soucis lorsque vous avez développé l'appli beta ?

Les paramètres saisis pour le post HTTP (j'ai modifié les id des 3 appareils) : 
`
{
"scale":"1month",
"home":
    {"rooms":
        [{"type":"sum_energy_elec_heating",
        "id":"_IDROOM_",
        "bridge":"_@RADIATEUR_"
        }],
	"id":"_IDHOME_"
	}
}
`
![image](https://github.com/shun84/jeedom-plugin-mullerintuitiv/assets/167800817/8a44ac53-b5b9-4c86-b20e-3bcae9cbd8eb)

**Comment by shun84** [comment]
Re, non en gros il y a un soucis sur votre json, c'est des *array*, il
manque date_end et date_begin

**Comment by Yann0128** [comment]
Ah merci, je pensais qu´ils etaient optinonnels comme chez Netatmo. Mais même en rajoutant ces deux champs, j'obtiens des erreurs 21 a chaque tentative. Vous auriez un exemple de la requête envoyée par Intuis connect ?
(je n'ai pas réussi a sniffer l'appli avec HTTP Toolkit)

**Comment by Yann0128** [comment]
C’est bon, j’ai trouvé une trame modèle. Merci pour votre aide ☺️
